config/routes.rb
Rails.application.routes.draw do

  resources :fights
  post '/fights/:id/play/:player', to: 'fights#play', as: 'play'
  get '/fights/:id/play/:player', to: 'fights#play'

  resources :players
  root 'static_pages#home'

  get 'static_pages/home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :featuring
  has_many :players, through: :featuring
end

app/models/featuring.rb
class Featuring < ApplicationRecord
  belongs_to :feature
  belongs_to :player
end

app/models/fight.rb
# == Schema Information
#
# Table name: fights
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  player_1   :integer
#  player_2   :integer
#  winner     :integer
#  summary    :text
#  weapon_1   :integer
#  weapon_2   :integer
#

class Fight < ApplicationRecord
  belongs_to :first_player, foreign_key: 'player_1', class_name: 'Player'
  belongs_to :second_player, foreign_key: 'player_2', class_name: 'Player'

  belongs_to :first_weapon, foreign_key: 'weapon_1', class_name: 'Weapon'
  belongs_to :second_weapon, foreign_key: 'weapon_2', class_name: 'Weapon'

  belongs_to :has_won, foreign_key: 'winner', class_name: 'Player', optional: true


  validates :first_player, presence: true
  validates :second_player, presence: true
  validates :first_weapon, presence: true
  validates :second_weapon, presence: true

  validates :summary, length: { maximum: 1000 }, allow_nil: true
  validate :are_not_the_same

  def are_not_the_same
    if player_1 == player_2
      errors.add(:players, 'Cannot choose the same player twice')
    end
  end


  def loser
    Player.find(lost)
  end

  def lost
    has_won.id == player_1 ? player_2 : player_1
  end



end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                 :integer          not null, primary key
#  player_name        :string
#  life_points        :integer
#  attack_points      :integer
#  experience         :integer          default(0)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  victories          :integer          default(0)
#  defeats            :integer          default(0)
#

class Player < ApplicationRecord

  has_many :home_fights, foreign_key: 'player_1', class_name: 'Fight'
  has_many :away_fights, foreign_key: 'player_2', class_name: 'Fight'
  has_many :wins, foreign_key: 'winner', class_name: 'Fight'

  has_many :featuring, dependent: :destroy
  has_many :features, through: :featuring

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

  validates :player_name, presence: true, length: { maximum: 60 }, uniqueness: true
  validates :life_points, presence: true, numericality: { greater_than_or_equal_to: 70, less_than_or_equal_to: 100 }
  validates :attack_points, presence: true, numericality: { greater_than_or_equal_to: 15, less_than_or_equal_to: 30 }
  validates :experience, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :victories, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :defeats, presence: true, numericality: { greater_than_or_equal_to: 0 }


end

app/models/weapon.rb
# == Schema Information
#
# Table name: weapons
#
#  id           :integer          not null, primary key
#  name         :string
#  bonus_damage :integer
#  weight       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Weapon < ApplicationRecord
  validates :name, presence: true, length: { maximum: 60 }, uniqueness: true
  validates :bonus_damage, presence: true, numericality: { greater_than_or_equal_to: 5, less_than_or_equal_to: 30 }
  validates :weight, presence: true, numericality: { greater_than_or_equal_to: 5, less_than_or_equal_to: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def new
    @fight = Fight.new
  end

  def create
    @fight = Fight.new(fight_params)

    respond_to do |format|
      if @fight.save
        format.html { redirect_to edit_fight_path(@fight), notice: 'Begin !' }
        format.json { render :show, status: :created, location: edit_fight_path(@fight) }
      else
        format.html { render :new }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @fight = Fight.find(params[:id])
    if @fight.has_won
      respond_to do |format|
        format.html { render :show }
      end
    end
    session[:game_status] = { first_player_life: @fight.first_player.life_points,
                              second_player_life: @fight.second_player.life_points,
                              summary: [],
                              winner: 0 }
  end

  def play
    @fight = Fight.find(params[:id])
    battle
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  def update
    @fight = Fight.find(params[:id])

    @fight.first_player.update_attribute(:experience, @fight.first_player.experience + 100)
    @fight.second_player.update_attribute(:experience, @fight.second_player.experience + 100)

    winner = Player.find(session[:game_status]["winner"])
    summary = session[:game_status]["summary"].join("\n")

    if @fight.update(has_won: winner, summary: summary)
      @fight.has_won.update_attribute(:victories, @fight.has_won.victories + 1)
      @fight.loser.update_attribute(:defeats, @fight.loser.defeats + 1)
      respond_to do |format|
        format.html { render :show }
      end
    end
  end

  def index
    @fights = Fight.all
  end

  def show
    @fight = Fight.find(params[:id])
  end

  private

  def battle
    @game = Game.new(@fight, session[:game_status], params[:player])
    session[:game_status] = @game.play
  end

  def fight_params
    params.require(:fight).permit(:player_1, :player_2, :winner, :weapon_1, :weapon_2)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
    @player.featuring.build
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to new_fight_path, notice: 'Player was successfully created.' }
        format.json { render new_fight_path, status: :created, location: new_fight_path }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def player_params
    params.require(:player).permit(:player_name, :life_points, :attack_points, :image, :experience, feature_ids: [])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/fights/_end.html.erb
<% if @game.status["winner"] > 0 %>
  <%= button_to 'View stats', fight_path, :method => :patch, class:"btn btn-block btn-dark btn-lg mt-3" %>
<% else %>
  <h2 class="text-center" id="battle">VERSUS</h2>
<% end %>

app/views/fights/_form.html.erb
<%= form_with(model: fight, local: true,:html => {:class => 'form-horizontal'}) do |form| %>
  <% if fight.errors.any? %>
    <div class="row">
      <div class="col-12">
        <div id="error_explanation">
          <h2><%= pluralize(fight.errors.count, "error") %> prohibited this fight from being saved:</h2>
          <ul>
            <% fight.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-12">
      <div class="form-row">
        <div class="form-group col-sm-6">
          <%= form.label :player_1 %>
          <%= form.collection_select :player_1, Player.all, :id, :player_name, {}, {:class=>'form-control'} %>
          <%= form.collection_select :weapon_1, Weapon.all, :id, :name, {}, {:class=>'form-control'} %>
        </div>
        <div class="form-group col-sm-6">
          <%= form.label :player_2 %>
          <%= form.collection_select :player_2, Player.all, :id, :player_name, {}, {:class=>'form-control'} %>
          <%= form.collection_select :weapon_2, Weapon.all, :id, :name, {}, {:class=>'form-control'} %>
        </div>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-12">
      <%= form.submit "fight", class: "btn btn-danger btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/fights/_hit.html.erb
<%= @hit %>

app/views/fights/_life_1st.html.erb
<div class="progress-bar bg-success" id="player_1" role="progressbar" style='width: <%= @game.status["first_player_life"] %>%' aria-valuenow='<%= @game.status["first_player_life"] %>' aria-valuemin="0" aria-valuemax="100" ></div>

app/views/fights/_life_2nd.html.erb
<div class="progress-bar bg-success" id="player_2" role="progressbar" style='width: <%= @game.status["second_player_life"] %>%' aria-valuenow='<%= @game.status["second_player_life"] %>' aria-valuemin="0" aria-valuemax="100" ></div>

app/views/fights/_play.html.erb
<%= @game.status["summary"].last %>

app/views/fights/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-group">
        <div class="card text-white bg-dark mt-5">
          <div class="card-header">
            <h2 class="text-center"> <%= @fight.first_player.player_name %></h2>
          </div>
          <div class="card-body">
            <%= image_tag @fight.first_player.image, class:"img-thumbnail mx-auto d-block" %>
            <% unless @fight.winner %>
              <%= link_to 'Attack', play_path(player: "first_player"), remote: true, class:"btn btn-block btn-danger btn-lg mt-3" %>
            <% end %>
          </div>
          <div class="card-footer">
            <div class="progress" id="life_1st">
              <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
        <div class="card bg-danger text-white mt-5">
          <div class="card-header">
            <h2 class="text-center" id="battle">VERSUS</h2>
          </div>
          <div class="card-body" id="ring">
          </div>
          <div class="card-footer">
          </div>
        </div>
        <div class="card bg-dark text-white mt-5">
          <div class="card-header">
            <h2 class="text-center"> <%= @fight.second_player.player_name %></h2>
          </div>
          <div class="card-body">
            <%= image_tag @fight.second_player.image, class:"img-thumbnail mx-auto d-block" %>
            <% unless @fight.winner %>
              <%= link_to 'Attack', play_path(player: "second_player"), remote: true, class:"btn btn-block btn-danger btn-lg mt-3" %>
            <% end %>
          </div>
          <div class="card-footer">
            <div class="progress" id="life_2nd">
              <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/fights/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12">
      <div class="card bg-white">
        <div class="card-body">
          <table class="table table-hover">
            <thead class="bg-primary text-white">
              <tr>
                <th>#</th>
                <th>First player</th>
                <th>Second player</th>
                <th>Winner</th>
                <th>Winner's victories</th>
                <th>Winner's experience</th>
                <th>Summary</th>
              </tr>
            </thead>
            <tbody>
              <% @fights.each do |fight| %>
                <tr>
                  <th>#<%= fight.id %></th>
                  <td><%= fight.first_player.player_name %></td>
                  <td><%= fight.second_player.player_name %></td>
                  <% if fight.winner %>
                    <td><%= fight.has_won.player_name %></td>
                    <td><%= fight.has_won.victories %></td>
                    <td><%= fight.has_won.experience %></td>
                  <% else %>
                    <td>Fight not finished</td>
                    <td><%= link_to "Come back to fight", edit_fight_path(fight) %></td>
                    <td></td>
                  <% end %>
                  <td><%= link_to "show", fight_path(fight) %></td>
                </tr>
              <% end  %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/fights/new.html.erb
<div class="container">
  <div class="card mt-5">
    <div class="card-body">
      <h1 class="card-title">Select your player</h1>
      <%= render 'form', fight: @fight %>
    </div>
  </div>
</div>

app/views/fights/play.js.erb
$('#ring').html("<%= j (render 'play') %>");
$('#battle').html("<%= j (render 'end') %>");
$('#life_1st').html("<%= j (render 'life_1st') %>");
$('#life_2nd').html("<%= j (render 'life_2nd') %>");

app/views/fights/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-group">
        <div class="card text-white bg-dark mt-5">
          <div class="card-header">
            <h2 class="text-center"> <%= @fight.first_player.player_name %></h2>
          </div>
          <div class="card-body">
            <%= image_tag @fight.first_player.image, class:"img-thumbnail mx-auto d-block" %>
            <% unless @fight.has_won %>
              <%= link_to 'Attack', play_path(player: "first_player"), remote: true, class:"btn btn-block btn-danger btn-lg mt-3" %>
            <% end %>
          </div>
        </div>
        <div class="card bg-danger text-white mt-5">
          <div class="card-header">
            <h2 class="text-center" id="battle">Winner : <%= @fight.has_won.player_name %></h2>
          </div>
          <div class="card-body" id="ring">
            <h2>Summary</h2>
            <%=  simple_format(@fight.summary) %>
          </div>
        </div>
        <div class="card bg-dark text-white mt-5">
          <div class="card-header">
            <h2 class="text-center"> <%= @fight.second_player.player_name %></h2>
          </div>
          <div class="card-body">
            <%= image_tag @fight.second_player.image, class:"img-thumbnail mx-auto d-block" %>
            <% unless @fight.has_won %>
              <%= link_to 'Attack', play_path(player: "second_player"), remote: true, class:"btn btn-block btn-danger btn-lg mt-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Cheap Soul Calibur", root_path,  { :class => "navbar-brand"}  %>
      <%= link_to 'Players list', players_path,  { :class => "nav-item nav-link text-light"} %>
      <%= link_to 'Fights stats', fights_path,  { :class => "nav-item nav-link text-light"} %>
      <%= link_to "Play", new_fight_path, { :class => "nav-item nav-link text-light"} %>
      <%= link_to "Create player", new_player_path, { :class => "nav-item nav-link text-light"} %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Soulcalibur</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="h-100 soul_bg">
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-12">
      <div class="form-row">
        <div class="form-group col-sm-6">
          <%= form.label :player_name %>
          <%= form.text_field :player_name, id: :player_player_name, class: 'form-control' %>
          <%= form.label :image %>
          <div class="custom-file">
            <%= form.file_field :image, id: :player_image, class: 'custom-file-input' %>
            <label class="custom-file-label" for="customFile">Choose file</label>
          </div>
          <%= form.collection_select(:feature_ids, Feature.all, :id, :feature_name,
                              {}, {:class=>'form-control', :multiple => true} ) %>
        </div>
        <div class="form-group col-sm-6">
          <%= form.label :life_points %>
          <%= form.number_field :life_points, id: :player_life_points, class: 'form-control', placeholder:'must be between 70 and 100' %>
          <%= form.label :attack_points %>
          <%= form.number_field :attack_points, id: :player_attack_points, class: 'form-control', placeholder: 'must be between 15 and 30' %>
        </div>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-12">
      <%= form.submit "Add player", class: "btn btn-danger btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="container">
  <div class="card mt-5">
    <div class="card-body">
      <h1 class="card-title">Edit Player</h1>
      <%= render 'form', player: @player %>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12">
      <div class="card bg-white">
        <div class="card-body">
          <h1>Players</h1>
          <table class="table table-hover">
            <thead class="bg-primary text-white">
              <tr>
                <th>Player name</th>
                <th>Life points</th>
                <th>Attack points</th>
                <th>Profile pic</th>
                <th>Experience</th>
                <th>Victories</th>
                <th>Defeats</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @players.each do |player| %>
                <tr>
                  <td><%= player.player_name %></td>
                  <td><%= player.life_points %></td>
                  <td><%= player.attack_points %></td>
                  <td><%= image_tag(player.image.url(:thumb)) %></td>
                  <td><%= player.experience %></td>
                  <td><%= player.victories %></td>
                  <td><%= player.defeats %></td>
                  <td><%= link_to 'Edit', edit_player_path(player) %></td>
                  <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>
          <%= link_to 'New Player', new_player_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/players/new.html.erb
<div class="container">
  <div class="card mt-5">
    <div class="card-body">
      <h1 class="card-title">Create Player</h1>
      <%= render 'form', player: @player %>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Player name:</strong>
  <%= @player.player_name %>
</p>
<p>
  <strong>Life points:</strong>
  <%= @player.life_points %>
</p>
<p>
  <strong>Attack points:</strong>
  <%= @player.attack_points %>
</p>
<p>
  <strong>Profile pic:</strong>
  <%= @player.image %>
</p>
<p>
  <strong>Experience:</strong>
  <%= @player.experience %>
</p>
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/static_pages/home.html.erb
<div class="container h-100">
  <div class="row h-100 my-auto align-middle">
    <div class="col-2"></div>
    <div class="col-8 mt-5 align-middle">
      <div class="jumbotron bg-dark text-center">
        <h1 class="text-light">Welcome to Cheap Soul Calibur</h1>
        <p class="text-light">A fighting game with very few buttons and no animation.
          BUT, you'll see numbers go down and a player win. Ready? </p>
        <%= link_to "Create New Player", new_player_path, class: "btn btn-danger btn-lg mx-auto mt-3" %>
        <%= link_to "Fight", new_fight_path, class: "btn btn-danger btn-lg mx-auto mt-3 px-5" %>
      </div>
    </div>
    <div class="col-2"></div>
  </div>
</div>